# Configuration file
SCA_account: sca_account
SCA_username: sca_user
SCA_password: sca_password
SCA_proxy: 
SCA_url: 
SCA_api_url: https://eu.api-sca.checkmarx.net
SCA_auth_url: https://eu.platform.checkmarx.net/identity/connect/token
SMTP_server:
SMTP_port:
SMTP_tls:
SMTP_user:
SMTP_password:
Email_from:
Email_subject:
Email_body:

