# Configuration file
SCA_account: SC_account
SCA_username: SCA_user
SCA_password: SCA_password
#SCA_proxy: http://176.117.76.115:443
SCA_proxy: 
SCA_url: https://eu.sca.checkmarx.net
SCA_api_url: https://eu.api-sca.checkmarx.net
SCA_auth_url: https://eu.platform.checkmarx.net/identity/connect/token
nexus_server_url: 

# email Configuration
SMTP_server: 
SMTP_port: 
SMTP_tls: 
SMTP_user: 
SMTP_password: 
Email_from: 
Email_subject: SCA vulnerabilities alert
Email_body: "Scan results URL: "



